stages:
  - build

.build:
  stage: build
  image: docker:20.10.16
  services:
  - alias: docker
    name: registry.gitlab.com/2ndwatch/docker-images/dind/dind:v1.0.3
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: /certs
    DOCKER_CERT_PATH: /certs/client
    DOCKER_TLS_VERIFY: 1
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - apk add --no-cache --upgrade git make tree
    - git config --global user.email productengineeringaccounts@2ndwatch.com
    - git config --global user.name 'Git Lab'
    - tree $HOME
    - ls -al $HOME
    - make setup ARGS="$TEMPLATE $CI_PROJECT_NAME" DOCKER_FLAGS=""
    - make run DOCKER_FLAGS="" | tee output.txt
    - |
      if [ "$(tail -n 1 output.txt)" != "Hello, world!" ]; then
        echo "Build failed. Output of app after performing `make run` was not 'Hello, world!'"
        tree .
        cat output.txt
      fi

build-go-int:
  extends: .build
  variables:
    TEMPLATE: go-int

build-java-ch:
  extends: .build
  variables:
    TEMPLATE: java-ch
