# DO NOT EDIT THIS FILE!
# This file is provided and managed by the ms-scaffolder repository. Any 
# modifications will be destroyed upon update. Please make any necessary 
# modifications in the ms-scaffolder repository:
# https://gitlab.com/2ndwatch/microservices/templates/ms-scaffolder

ifneq (,$(wildcard ./.env))
	include .env
	export
endif

ifeq ($(OS),Windows_NT)
	CURRENT_UID := 0
	CURRENT_GID := 0
else
	CURRENT_UID := $(shell id -u)
	CURRENT_GID := $(shell id -g)
endif

export CURRENT_UID
export CURRENT_GID

SCAFFOLDER_RUNNER_IMAGE=registry.gitlab.com/2ndwatch/docker-images/ms-scaffolder-runner/ms-scaffolder-runner:1
ARGS=

dockerinit:
	docker login registry.gitlab.com
	docker pull ${SCAFFOLDER_RUNNER_IMAGE} || echo "Continue on pull fail incase we are testing a local image"
ifdef BUILD_IMAGE
	docker pull ${BUILD_IMAGE} || echo "Continue on pull fail incase we are testing a local image"
endif

shapp: dockerbuild
ifdef BUILD_IMAGE
	docker run --rm -it \
	-v "${CURDIR}":/app \
	-v "${HOME}/.gitconfig":/etc/gitconfig \
	-u ${CURRENT_UID}:${CURRENT_GID} \
	${PROJECT_SLUG} \
	sh
else
	$(error This command cannot be used until after running `make setup`)
endif

shbuilder: dockerinit
ifdef BUILD_IMAGE
	docker run --rm -it \
	-v "${CURDIR}":/app \
	-v "${HOME}/.gitconfig":/etc/gitconfig \
	-u ${CURRENT_UID}:${CURRENT_GID} \
	${BUILD_IMAGE} \
	bash
else
	$(error This command cannot be used until after running `make setup`)
endif

shrunner: dockerinit
	docker run --rm -it \
	-v "${CURDIR}":/app \
	-v "${HOME}/.gitconfig":/etc/gitconfig \
	-u ${CURRENT_UID}:${CURRENT_GID} \
	${SCAFFOLDER_RUNNER_IMAGE} \
	bash

setup: dockerinit
ifndef BUILD_IMAGE
	docker run --rm -it \
	-v "${CURDIR}":/app \
	-v "${HOME}/.gitconfig":/etc/gitconfig \
	-u ${CURRENT_UID}:${CURRENT_GID} \
	${SCAFFOLDER_RUNNER_IMAGE} \
	bash -c 'cd /app && ./scripts/ms-scaffolder/setup.sh $(ARGS)'
else
	$(error You have already set up this project.)
endif

update: dockerinit
ifdef BUILD_IMAGE
	git clone git@gitlab.com:2ndwatch/microservices/templates/ms-scaffolder.git "${CURDIR}/.ms-scaffolder"
	docker run --rm -it \
	-v "${CURDIR}":/app \
	-v "${HOME}/.gitconfig":/etc/gitconfig \
	-u ${CURRENT_UID}:${CURRENT_GID} \
	${SCAFFOLDER_RUNNER_IMAGE} \
	bash -c \
	'cd /app && \
	cp ./scripts/ms-scaffolder/update.sh ./.ms-scaffolder/update-temp.sh && \
	./.ms-scaffolder/update-temp.sh $(ARGS)'
else
	$(error This command cannot be used until after running `make setup`)
endif

protogen: dockerinit
ifdef BUILD_IMAGE
	docker run --rm -it \
	-v "${CURDIR}":/app \
	-u ${CURRENT_UID}:${CURRENT_GID} \
	${BUILD_IMAGE} \
	bash -c 'cd /app && ./scripts/ms-scaffolder/protogen.sh $(ARGS)'
else
	$(error This command cannot be used until after running `make setup`)
endif

build: dockerinit
ifdef BUILD_IMAGE
	docker run --rm -it \
	-v "${CURDIR}":/app \
	-v ~/.gitconfig:/etc/gitconfig \
	-u ${CURRENT_UID}:${CURRENT_GID} \
	${BUILD_IMAGE} \
	bash -c 'cd /app && ./scripts/ms-scaffolder/build.sh $(ARGS)'
else
	$(error This command cannot be used until after running `make setup`)
endif

test: dockerinit
ifdef BUILD_IMAGE
	docker run --rm -it \
	-v "${CURDIR}":/app \
	-u ${CURRENT_UID}:${CURRENT_GID} \
	${BUILD_IMAGE} \
	bash -c 'cd /app && ./scripts/ms-scaffolder/test.sh $(ARGS)'
else
	$(error This command cannot be used until after running `make setup`)
endif

dockerbuild: build
ifdef BUILD_IMAGE
	docker build -t ${PROJECT_SLUG} ${CURDIR} --build-arg JARFILE=${PROJECT_SLUG}.jar
else
	$(error This command cannot be used until after running `make setup`)
endif

run: dockerbuild
ifdef BUILD_IMAGE
	docker run --rm -it ${PROJECT_SLUG}
else
	$(error This command cannot be used until after running `make setup`)
endif

.PHONY: all dockerinit execrunner setup update protogen build test run 
