mslib:
  deployment:
    ms-admissions-api:
      image: registry.gitlab.com/2ndwatch/microservices/ms-admissions-service/api
      imageTag: 0
      imagePullPolicy: Always
      serviceAccountName: ms-admissions-api

  serviceAccount:
    ms-admissions-api:
      annotations:
        eks.amazonaws.com/role-arn: REPLACE